version: '2'
services:
 lb:
   image: dockercloud/haproxy:1.6.2
   links:
     - registry
     - gitlab
   ports:
     - '80:80'
     - '443:443'
     - '5000:5000'
   restart: always
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
 registry:
   build: ./registry
   restart: always
   expose:
     - 5000
   environment:
     TCP_PORTS: '5000'
     VIRTUAL_HOST: '*:5000, https://*:5000'
     FORCE_SSL: 'false'
     REGISTRY_STORAGE_DELETE_ENABLED: 'true'
   volumes:
     - ./local/registry:/var/lib/registry
