version: '2'

services:
   gitlab:
      image: gitlab/gitlab-ce:latest
      restart: always
      ports:
         - 80
         - 443
         - 0.0.0.0:2222:22
      container_name: gitlab
      volumes:
         - ./gitlab/config:/etc/gitlab
         - ./gitlab/logs:/var/logs/gitlab
         - ./gitlab/data:/var/opt/gitlab
