version: '2'

services:
   gitlab:
      image: gitlab/gitlab-ce:latest
      restart: always
      ports: 
         - 0.0.0.0:80:80
         - 0.0.0.0:443:443
         - 0.0.0.0:22:22
      container_name: gitlab
